---
deployment:
  tasks:
    - export DEPLOYPATH=/home/petc6698/public_html/
    - tar --exclude='./config_db.php' --exclude='./.git' -cf deploy.tar .
    - tar -xf deploy.tar -C $DEPLOYPATH
    - rm deploy.tar
