---
deployment:
  tasks:
    - export DEPLOYPATH=/home/petc6698/public_html/
    - chmod 755 $DEPLOYPATH
    - find . -mindepth 1 -maxdepth 1 ! -name 'config_db.php' ! -name '.git' -exec cp -R {} $DEPLOYPATH \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
